#org.gradle.jvmargs=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
#-Dorg.gradle.debug=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8
jdkVersion=1.8
group=net.xdob.vexra
slf4j_version=1.7.36
logback_version=1.2.13
protobuf_version=3.25.5
grpc_version=1.77.0
netty_version=4.2.6.Final
dropwizard_version=4.2.21
lang3_version=3.8.1
gson_version=2.10.1
guava_version=33.3.1-jre
h2db_version=2.3.0
ldb_version=0.12.0-SNAPSHOT
#flyway_version=6.0.6
version=0.1.0-SNAPSHOT
