rootProject.name = 'vexra'
include 'vexra-proto'
include 'vexra-common'
include 'vexra-client'
include 'vexra-server-api'
include 'vexra-metrics-api'
include 'vexra-metrics-default'
include 'vexra-server-sm'
include 'vexra-server'
include 'vexra-grpc'
include 'vexra-netty'
include 'vexra-rmap'
include 'vexra-adb'
include 'vexra-ldb'