

dependencies {
    //implementation("org.apache.commons:commons-lang3:${lang3_version}")
//    implementation "com.google.code.gson:gson:${gson_version}"
    api("com.google.guava:guava:${guava_version}")
    //api("org.bouncycastle:bcprov-jdk18on:1.81")
    api("com.google.protobuf:protobuf-java:${protobuf_version}")
    api("com.google.protobuf:protobuf-java-util:${protobuf_version}")
    api("io.grpc:grpc-netty:${grpc_version}"){
        exclude group: 'io.netty'
    }
    implementation("io.grpc:grpc-protobuf:${grpc_version}"){
      exclude group: 'io.grpc', module: 'grpc-protobuf-lite'
    }
    api("io.netty:netty-codec:${netty_version}")
    api("io.netty:netty-codec-http2:${netty_version}")
    api("io.netty:netty-codec-http3:${netty_version}")
    api("io.netty:netty-handler:${netty_version}")
//    implementation "io.grpc:grpc-stub:${grpc_version}"
//    implementation "io.grpc:grpc-context:${grpc_version}"
    implementation platform("io.netty:netty-bom:${netty_version}")
//    implementation "io.dropwizard.metrics:metrics-core:${dropwizard_version}"
//    implementation "io.dropwizard.metrics:metrics-jvm:${dropwizard_version}"
//    implementation "io.dropwizard.metrics:metrics-jmx:${dropwizard_version}"
    api project(':vexra-proto')
    //api project(':vexra-fasts')
}
