
dependencies {
    api project(':vexra-proto')
    api project(':vexra-common')
    api project(':vexra-client')
    api project(':vexra-server-api')
    api project(':vexra-metrics-api')
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}